export const paths = {
  home: '/',
  login: '/login',
  register: '/register',
  admin: '/admin',
  adminArtists: '/admin/artists',
  adminClients: '/admin/clients',
  adminSystem: '/admin/system',
  artist: '/artist',
  artistAgenda: '/artist',
  artistAppointments: '/artist/appointments',
  artistServices: '/artist/services',
  artistClients: '/artist/clients',
  artistSettings: '/artist/settings',
  artistSchedule: '/artist/schedule',
  client: '/client',
  clientAppointments: '/client/appointments',
  clientExplore: '/client/search',
  clientSearch: '/client/search',
  clientFavorites: '/client/favorites',
}
