export const advancedAestheticsCatalog = {
  'Toxina botulínica': { 'Tratamiento de arrugas dinámicas': ['Líneas de frente', 'Entrecejo', 'Patas de gallo', 'Bunny lines/nariz', 'Líneas periorales', 'Sonrisa gingival', 'Elevación de ceja', 'Mentón empedrado', 'Bandas platismales/cuello', 'Bruxismo/maseteros', 'Hiperhidrosis axilar', 'Hiperhidrosis palmar', 'Hiperhidrosis plantar', 'Full face'] },
  'Rellenos con ácido hialurónico': { 'Relleno y armonización facial': ['Aumento/perfilado de labios', 'Surcos nasogenianos', 'Líneas de marioneta', 'Ojeras', 'Pómulos', 'Mentón', 'Línea mandibular', 'Sien', 'Arrugas periorales', 'Rinomodelación', 'Armonización facial'] },
  'Bioestimulación facial': { 'Bioestimulación y regeneración': ['Bioestimulador de colágeno', 'Hidroxiapatita cálcica', 'Ácido poli-L-láctico', 'Polinucleótidos/PDRN', 'Skin boosters', 'Bioestimulación facial integral'] },
  Mesoterapia: { 'Mesoterapia especializada': ['Mesoterapia facial', 'Capilar', 'Corporal', 'Revitalización', 'Hidratación', 'Mesoterapia para adiposidad localizada'] },
  'PRP / Plasma rico en plaquetas': { 'Regeneración con PRP': ['PRP facial', 'PRP capilar', 'PRP cuello/escote', 'Rejuvenecimiento con PRP'] },
  'Hilos tensores': { 'Lifting y soporte con hilos': ['Hilos PDO', 'Hilos lisos', 'Hilos espiculados/tensores', 'Lifting facial con hilos', 'Definición mandibular', 'Elevación de ceja'] },
  'Microneedling / Dermapen': { 'Microneedling especializado': ['Rejuvenecimiento facial', 'Cicatrices de acné', 'Poros/textura', 'Manchas', 'Estrías', 'Microneedling capilar'] },
  'Peelings químicos': { 'Peeling profesional': ['Superficial', 'Medio', 'Antiacné', 'Despigmentante', 'Rejuvenecimiento', 'Luminosidad', 'Peeling personalizado'] },
  'Limpieza facial profesional': { 'Facial profesional': ['Limpieza profunda', 'Extracción de comedones', 'Facial hidratante', 'Facial antiacné', 'Facial piel sensible', 'Facial antioxidante', 'Facial antiedad'] },
  'Hydrofacial / Hidrodermoabrasión': { 'Hidrodermoabrasión facial': ['Limpieza e hidratación', 'Extracción', 'Rejuvenecimiento', 'Luminosidad', 'Tratamiento completo'] },
  Microdermoabrasión: { 'Renovación con microdermoabrasión': ['Punta de diamante', 'Renovación facial', 'Manchas superficiales', 'Textura/poros', 'Corporal'] },
  'Radiofrecuencia facial': { 'Radiofrecuencia por zona': ['Rostro completo', 'Papada', 'Cuello', 'Escote', 'Contorno de ojos', 'Radiofrecuencia fraccionada'] },
  'Radiofrecuencia corporal': { 'Reafirmación corporal por zona': ['Abdomen', 'Brazos', 'Muslos', 'Glúteos', 'Flancos', 'Espalda', 'Tratamiento reafirmante'] },
  'HIFU / Ultrasonido focalizado': { 'HIFU por zona': ['Rostro', 'Papada', 'Cuello', 'Línea mandibular', 'Abdomen', 'Brazos', 'Muslos', 'Corporal'] },
  'Ultrasonido estético': { 'Ultrasonido por objetivo': ['Facial', 'Corporal', 'Adiposidad localizada', 'Reafirmación', 'Sonoforésis'] },
  Cavitación: { 'Cavitación por zona': ['Abdomen', 'Flancos', 'Brazos', 'Muslos', 'Espalda', 'Adiposidad localizada'] },
  Criolipólisis: { 'Criolipólisis por zona': ['Abdomen', 'Flancos', 'Espalda', 'Brazos', 'Muslos', 'Papada'] },
  'Electroestimulación corporal': { 'Tonificación por zona': ['Abdomen', 'Glúteos', 'Brazos', 'Piernas', 'Tonificación muscular'] },
  Presoterapia: { 'Presoterapia y recuperación': ['Piernas', 'Abdomen', 'Brazos', 'Cuerpo completo', 'Drenaje/recuperación'] },
  Vacumterapia: { 'Vacumterapia por objetivo': ['Glúteos', 'Piernas', 'Abdomen', 'Celulitis', 'Moldeo corporal'] },
  'Láser dermatológico/estético': { 'Láser por indicación': ['Rejuvenecimiento', 'Manchas', 'Cicatrices de acné', 'Poros/textura', 'Lesiones vasculares', 'Resurfacing'] },
  'IPL / Luz pulsada intensa': { 'IPL por indicación': ['Fotorejuvenecimiento', 'Manchas', 'Enrojecimiento', 'Lesiones vasculares superficiales', 'Depilación IPL'] },
  'Depilación láser': { 'Depilación corporal': ['Rostro', 'Axilas', 'Brazos', 'Bikini', 'Bikini brasileño', 'Piernas', 'Espalda', 'Pecho', 'Abdomen', 'Cuerpo completo'] },
  'Eliminación de tatuajes': { 'Eliminación por tamaño o tipo': ['Tatuaje pequeño', 'Mediano', 'Grande', 'Maquillaje permanente/microblading'] },
  'Tratamientos para manchas': { 'Tratamiento despigmentante': ['Melasma', 'Hiperpigmentación', 'Manchas solares', 'Hiperpigmentación postinflamatoria', 'Tratamiento combinado'] },
  'Tratamientos para acné': { 'Tratamiento integral de acné': ['Acné activo', 'Comedones', 'Control de sebo', 'Cicatrices de acné', 'Manchas postacné'] },
  'Rejuvenecimiento facial': { 'Plan de rejuvenecimiento': ['Facial antiedad', 'Reafirmación', 'Arrugas finas', 'Textura', 'Luminosidad', 'Tratamiento combinado'] },
  'Contorno facial no quirúrgico': { 'Armonización y contorno': ['Papada', 'Línea mandibular', 'Mentón', 'Pómulos', 'Armonización facial', 'Lifting no quirúrgico'] },
  'Tratamientos reductivos corporales': { 'Reducción por zona': ['Abdomen', 'Cintura/flancos', 'Brazos', 'Espalda', 'Muslos', 'Piernas', 'Tratamiento combinado'] },
  'Tratamientos reafirmantes': { 'Reafirmación por zona': ['Abdomen', 'Brazos', 'Muslos', 'Glúteos', 'Cuello', 'Corporal'] },
  'Tratamiento de celulitis': { 'Tratamiento anticelulitis': ['Piernas', 'Muslos', 'Glúteos', 'Tratamiento combinado'] },
  'Drenaje linfático': { 'Drenaje por zona': ['Manual', 'Facial', 'Piernas', 'Abdomen', 'Cuerpo completo', 'Postprocedimiento'] },
  'Masaje estético corporal': { 'Masaje por objetivo': ['Reductivo', 'Modelador', 'Reafirmante', 'Anticelulitis', 'Relajante'] },
  'Tratamiento de estrías': { 'Tratamiento de estrías por técnica': ['Microneedling', 'Láser', 'Radiofrecuencia', 'Peeling', 'Tratamiento combinado'] },
  'Tratamientos capilares estéticos': { 'Estimulación capilar': ['PRP capilar', 'Microneedling capilar', 'Mesoterapia capilar', 'Estimulación capilar'] },
  'Escleroterapia / tratamiento vascular estético': { 'Tratamiento vascular por zona': ['Telangiectasias', 'Arañas vasculares', 'Tratamiento por zona'] },
  'Enzimas / tratamientos inyectables localizados': { 'Tratamiento inyectable localizado': ['Papada', 'Adiposidad localizada', 'Tratamiento corporal localizado'] },
  'Valoración de medicina estética': { 'Consulta de valoración': ['Primera valoración', 'Seguimiento', 'Plan facial', 'Plan corporal', 'Valoración para procedimiento inyectable'] },
}

export const customVariantOption = 'Personalizado'
