export const artistProfile = {
  studioId: 'studio-glow',
  name: 'Valeria Moon Studio',
  role: 'Artista principal',
  location: 'Polanco, CDMX',
  rating: '4.9',
  plan: 'Studio Pro',
  occupancy: '82%',
}

export const artistAppointments = [
  {
    studioId: 'studio-glow',
    time: '09:30',
    end: '10:15',
    clientId: 'client-mf',
    client: 'María Fernanda',
    service: 'Laminado de ceja',
    duration: '45 min',
    status: 'Confirmada',
    room: 'Suite Rose',
    type: 'appointment',
    date: '2026-05-18',
    grossAmount: 420,
    platformFee: 42,
    artistRevenue: 378,
    serviceTier: 'medium',
    rewardApplied: null,
    pointsGranted: 60,
    riskScore: 'low',
    appointmentStatus: 'scheduled',
  },
  {
    studioId: 'studio-glow',
    time: '11:00',
    end: '12:10',
    clientId: 'client-ct',
    client: 'Camila Torres',
    service: 'Lash lifting',
    duration: '70 min',
    status: 'Por llegar',
    room: 'Suite Nude',
    type: 'appointment',
    date: '2026-05-18',
    grossAmount: 680,
    platformFee: 68,
    artistRevenue: 612,
    serviceTier: 'premium',
    rewardApplied: null,
    pointsGranted: 90,
    riskScore: 'low',
    appointmentStatus: 'scheduled',
  },
  {
    studioId: 'studio-glow',
    time: '14:00',
    end: '15:00',
    client: 'Descanso',
    clientId: null,
    service: 'Bloque no disponible',
    duration: '60 min',
    status: 'Descanso',
    room: 'Agenda',
    type: 'break',
    date: '2026-05-18',
    grossAmount: 0,
    platformFee: 0,
    artistRevenue: 0,
    serviceTier: null,
    rewardApplied: null,
    pointsGranted: 0,
    riskScore: 'low',
    appointmentStatus: 'scheduled',
  },
  {
    studioId: 'studio-glow',
    time: '16:00',
    end: '17:30',
    clientId: 'client-as',
    client: 'Ana Sofía',
    service: 'Makeup social',
    duration: '90 min',
    status: 'Anticipo',
    room: 'Makeup bar',
    type: 'appointment',
    date: '2026-05-18',
    grossAmount: 1250,
    platformFee: 125,
    artistRevenue: 1125,
    serviceTier: 'vip',
    rewardApplied: null,
    pointsGranted: 120,
    riskScore: 'low',
    appointmentStatus: 'scheduled',
  },
]

export const artistClients = [
  {
    id: 'client-mf',
    studioId: 'studio-glow',
    name: 'María Fernanda',
    phone: '55 1234 5678',
    birthday: '1993-03-18',
    flowPoints: 98,
    vipTier: 'Glow',
    streak: 4,
    totalVisits: 14,
    pointsExpirationDate: '2026-12-31',
    preferredServices: ['Lash lifting', 'Brow design'],
    favoriteArtist: 'Valeria Moon',
    lastVisit: '2026-05-05',
    nextRecommendedVisit: '2026-05-25',
    rewardsHistory: [
      { event: 'Aniversario VIP', points: 30, date: '2026-04-01' },
      { event: 'Reserva premium', points: 20, date: '2026-03-15' },
    ],
    notes: 'Cliente fiel de tardes, prefiere acabados naturales.',
  },
  {
    id: 'client-as',
    studioId: 'studio-glow',
    name: 'Ana Sofía',
    phone: '55 9876 5432',
    birthday: '1995-10-12',
    flowPoints: 72,
    vipTier: 'Glow',
    streak: 2,
    totalVisits: 9,
    pointsExpirationDate: '2026-10-30',
    preferredServices: ['Brow design', 'Soft glam makeup'],
    favoriteArtist: 'Valeria Moon',
    lastVisit: '2026-04-28',
    nextRecommendedVisit: '2026-05-22',
    rewardsHistory: [
      { event: 'Check-in bonus', points: 15, date: '2026-04-28' },
    ],
    notes: 'Le gusta combinar cejas y maquillaje para eventos.',
  },
  {
    id: 'client-ct',
    studioId: 'studio-glow',
    name: 'Camila Torres',
    phone: '55 1122 3344',
    birthday: '1990-06-02',
    flowPoints: 124,
    vipTier: 'Glow',
    streak: 7,
    totalVisits: 21,
    pointsExpirationDate: '2027-01-15',
    preferredServices: ['Lash lifting', 'Microblading'],
    favoriteArtist: 'Valeria Moon',
    lastVisit: '2026-05-10',
    nextRecommendedVisit: '2026-05-20',
    rewardsHistory: [
      { event: 'Tercer servicio mensual', points: 25, date: '2026-05-10' },
    ],
    notes: 'Cliente VIP, muy activa en promociones de loyalty.',
  },
]

export const artistServices = [
  { name: 'Lash lifting', category: 'Colocación de Pestañas', price: 680, duration: '70 min', bookings: 18, demand: 'Alta', status: 'Activo', serviceTier: 'premium' },
  { name: 'Brow design', category: 'Microblading', price: 420, duration: '45 min', bookings: 24, demand: 'Top', status: 'Activo', serviceTier: 'medium' },
  { name: 'Soft glam makeup', category: 'Maquillaje', price: 1250, duration: '90 min', bookings: 11, demand: 'Media', status: 'Suspendido', serviceTier: 'vip' },
]

export const serviceCatalog = {
  'Colocación de Uñas': [
    'Uñas acrílicas',
    'Uñas en gel',
    'Uñas postizas',
    'Ombré nails',
    'Diseño personalizado',
    'Nail art',
    'Uñas decoradas',
    'Extensión de uñas',
    'Uñas 3D',
  ],
  'Colocación de Pestañas': [
    'Pestañas volumen ruso',
    'Pestañas volumen clásico',
    'Pestañas volumen híbrido',
    'Pestañas de seda',
    'Pestañas de visón',
    'Refuerzos de pestañas',
    'Desmaquillante de pestañas',
  ],
  Maquillaje: [
    'Maquillaje de novia',
    'Maquillaje casual',
    'Maquillaje de quinceaños',
    'Maquillaje de evento social',
    'Maquillaje de fiesta',
    'Maquillaje de graduación',
    'Maquillaje artístico',
    'Maquillaje fantasía',
    'Maquillaje smoke eyes',
    'Maquillaje natural',
    'Maquillaje glam',
    'Maquillaje corporativo',
    'Maquillaje de sesión fotográfica',
  ],
  Manicure: [
    'Manicure clásico',
    'Manicure francés',
    'Manicure gel',
    'Manicure spa',
    'Manicure con diseño',
    'Manicure semipermanente',
    'Manicure para eventos',
    'Manicure reparador',
    'Manicure con piedras',
  ],
  Pedicure: [
    'Pedicure clásico',
    'Pedicure francés',
    'Pedicure gel',
    'Pedicure spa',
    'Pedicure con diseño',
    'Pedicure semipermanente',
    'Pedicure para eventos',
    'Pedicure reparador',
    'Pedicure con piedras',
    'Pedicure terapéutico',
  ],
  Microblading: [
    'Microblading cejas',
    'Microblading con sombreado',
    'Microblading de pelo a pelo',
    'Diseño de cejas',
    'Corrección de cejas',
    'Micropigmentación labios',
    'Micropigmentación delineado',
  ],
  Faciales: [
    'Limpieza facial profunda',
    'Facial con ácido glicólico',
    'Facial con ácido salicílico',
    'Facial hidratante',
    'Facial antienvejecimiento',
    'Facial antiacné',
    'Facial descongestionante',
    'Facial con mascarilla de colágeno',
    'Facial con retinol',
    'Facial vitamínico',
    'Peeling facial',
    'Facial luminoso',
    'Facial para pieles sensibles',
    'Facial oxigenante',
  ],
  Depilado: [
    'Depilación con cera',
    'Depilación con hilo',
    'Depilación láser',
    'Depilación de cejas',
    'Depilación de bigote',
    'Depilación de axilas',
    'Depilación de piernas',
    'Depilación de brazos',
    'Depilación de espalda',
    'Depilación de zona íntima',
    'Depilación facial',
    'Depilación con azúcar',
  ],
}

export const weeklySchedule = [
  { day: 'Lunes', active: true, start: '10:00', end: '19:00', breakStart: '14:00', breakEnd: '15:00' },
  { day: 'Martes', active: true, start: '10:00', end: '18:00', breakStart: '14:30', breakEnd: '15:00' },
  { day: 'Miércoles', active: true, start: '11:00', end: '19:00', breakStart: '15:00', breakEnd: '15:30' },
  { day: 'Jueves', active: true, start: '10:00', end: '18:00', breakStart: '14:00', breakEnd: '15:00' },
  { day: 'Viernes', active: true, start: '10:00', end: '17:00', breakStart: '13:30', breakEnd: '14:00' },
  { day: 'Sábado', active: false, start: 'Libre', end: 'Libre', breakStart: '-', breakEnd: '-' },
  { day: 'Domingo', active: false, start: 'Libre', end: 'Libre', breakStart: '-', breakEnd: '-' },
]

export const recurringClients = [
  { name: 'Mariana L.', visits: 12, next: 'Mie 15', value: '$8.4K' },
  { name: 'Camila R.', visits: 9, next: 'Vie 17', value: '$6.1K' },
  { name: 'Renata M.', visits: 7, next: 'Lun 20', value: '$4.8K' },
]

export const clientAppointments = [
  { artist: 'Valeria Moon', service: 'Lash lifting', date: 'Miercoles 15', time: '11:00', address: 'Polanco' },
  { artist: 'Nude Beauty Lab', service: 'Facial glow', date: 'Sabado 18', time: '13:30', address: 'Roma Norte' },
]

export const favoriteArtists = [
  { name: 'Valeria Moon', specialty: 'Lashes & brows', rating: '4.9', distance: '1.8 km', nextSlot: 'Hoy 17:30' },
  { name: 'Nude Beauty Lab', specialty: 'Skin care', rating: '4.8', distance: '3.2 km', nextSlot: 'Manana 12:00' },
  { name: 'Aura Nails', specialty: 'Nail art premium', rating: '4.9', distance: '4.1 km', nextSlot: 'Vie 10:00' },
]

export const clientHistory = [
  { service: 'Brow design', artist: 'Valeria Moon', date: 'Abr 28', amount: '$420' },
  { service: 'Facial glow', artist: 'Nude Beauty Lab', date: 'Abr 12', amount: '$950' },
  { service: 'Nail art premium', artist: 'Aura Nails', date: 'Mar 30', amount: '$720' },
]

export const adminMetrics = [
  { label: 'Reservas del mes', value: '2,184', trend: '+18%' },
  { label: 'Ingresos procesados', value: '$1.28M', trend: '+12%' },
  { label: 'Artistas activas', value: '348', trend: '+31' },
  { label: 'Clientes registradas', value: '12.6K', trend: '+9%' },
]

export const studios = [
  {
    id: 'studio-glow',
    name: 'Studio Glow Beauty',
    city: 'CDMX',
    specialty: 'Lashes, brows, makeup',
    studioStatus: 'approved',
    createdAt: '2026-04-18',
    totalArtists: 3,
    totalClients: 148,
    occupancy: 82,
    revenue: 84000,
    riskScore: 'low',
  },
  {
    id: 'studio-aura',
    name: 'Studio Aura Nails',
    city: 'Guadalajara',
    specialty: 'Nails, nail art, spa manicure',
    studioStatus: 'pending',
    createdAt: '2026-05-12',
    totalArtists: 2,
    totalClients: 12,
    occupancy: 36,
    revenue: 0,
    riskScore: 'medium',
  },
  {
    id: 'studio-velvet',
    name: 'Studio Velvet Skin',
    city: 'Monterrey',
    specialty: 'Skincare, faciales, brows',
    studioStatus: 'approved',
    createdAt: '2026-03-28',
    totalArtists: 4,
    totalClients: 96,
    occupancy: 74,
    revenue: 63000,
    riskScore: 'low',
  },
  {
    id: 'studio-muse',
    name: 'Casa Muse Beauty',
    city: 'Puebla',
    specialty: 'Peinado, makeup social, novias',
    studioStatus: 'pending',
    createdAt: '2026-05-14',
    totalArtists: 1,
    totalClients: 4,
    occupancy: 24,
    revenue: 0,
    riskScore: 'medium',
  },
  {
    id: 'studio-icon',
    name: 'Icon Brow Atelier',
    city: 'Queretaro',
    specialty: 'Microblading, brows',
    studioStatus: 'suspended',
    createdAt: '2026-04-30',
    totalArtists: 1,
    totalClients: 24,
    occupancy: 48,
    revenue: 12000,
    riskScore: 'high',
  },
]

export const users = [
  {
    id: 'user-platform-owner',
    name: 'Studio Flow HQ',
    email: 'owner@studioflow.mx',
    role: 'platform_owner',
    studioId: null,
    status: 'Activo',
  },
  {
    id: 'user-studio-owner-glow',
    name: 'Valeria Moon',
    email: 'valeria@studioflow.mx',
    role: 'studio_owner',
    studioId: 'studio-glow',
    status: 'Activo',
  },
  {
    id: 'user-manager-glow',
    name: 'Lucia Manager',
    email: 'manager.glow@studioflow.mx',
    role: 'studio_manager',
    studioId: 'studio-glow',
    status: 'Activo',
  },
  {
    id: 'user-artist-glow',
    name: 'Valeria Artist',
    email: 'artist.glow@studioflow.mx',
    role: 'artist',
    studioId: 'studio-glow',
    status: 'Activo',
  },
  {
    id: 'user-client-demo',
    name: 'Mariana Lopez',
    email: 'mariana@studioflow.mx',
    role: 'client',
    studioId: 'studio-glow',
    status: 'Activo',
  },
  {
    id: 'user-owner-velvet',
    name: 'Sofia Lab',
    email: 'sofia@studioflow.mx',
    role: 'studio_owner',
    studioId: 'studio-velvet',
    status: 'Activo',
  },
]

export const managedArtists = [
  {
    studioId: 'studio-glow',
    name: 'Valeria Moon Studio',
    city: 'CDMX',
    plan: 'Studio Pro',
    status: 'Activo',
    studioStatus: 'approved',
    registeredAt: '2026-04-18',
    specialties: ['Lashes', 'Brows', 'Makeup'],
    revenue: '$84K',
    owner: 'Valeria Moon',
  },
  {
    studioId: 'studio-aura',
    name: 'Aura Nails',
    city: 'Guadalajara',
    plan: 'Premium',
    status: 'Inactivo',
    studioStatus: 'pending',
    registeredAt: '2026-05-12',
    specialties: ['Nails', 'Nail art', 'Spa manicure'],
    revenue: '$0',
    owner: 'Renata Sol',
  },
  {
    studioId: 'studio-velvet',
    name: 'Nude Beauty Lab',
    city: 'Monterrey',
    plan: 'Studio Pro',
    status: 'Activo',
    studioStatus: 'approved',
    registeredAt: '2026-03-28',
    specialties: ['Skincare', 'Faciales', 'Brows'],
    revenue: '$63K',
    owner: 'Sofia Lab',
  },
  {
    studioId: 'studio-muse',
    name: 'Casa Muse Beauty',
    city: 'Puebla',
    plan: 'Studio Curated',
    status: 'Inactivo',
    studioStatus: 'pending',
    registeredAt: '2026-05-14',
    specialties: ['Peinado', 'Makeup social', 'Novias'],
    revenue: '$0',
    owner: 'Daniela Muse',
  },
  {
    studioId: 'studio-icon',
    name: 'Icon Brow Atelier',
    city: 'Queretaro',
    plan: 'Premium',
    status: 'Inactivo',
    studioStatus: 'suspended',
    registeredAt: '2026-04-30',
    specialties: ['Microblading', 'Brows'],
    revenue: '$12K',
    owner: 'Elena Ruiz',
  },
]

export const managedClients = [
  { studioId: 'studio-glow', name: 'Mariana Lopez', appointments: 12, status: 'Activo', segment: 'VIP', spend: '$8.4K' },
  { studioId: 'studio-velvet', name: 'Camila Ruiz', appointments: 7, status: 'Activo', segment: 'Frecuente', spend: '$4.2K' },
  { studioId: 'studio-aura', name: 'Ana Garza', appointments: 4, status: 'Inactivo', segment: 'Nueva', spend: '$1.8K' },
]

export const systemStatus = [
  { label: 'API', status: 'Preparada', tone: 'success', detail: 'Servicios listos para conectar' },
  { label: 'Supabase', status: 'Pendiente', tone: 'neutral', detail: 'Modulo reservado' },
  { label: 'Pagos', status: 'Pendiente', tone: 'neutral', detail: 'Checkout futuro' },
  { label: 'Autenticacion', status: 'Pendiente', tone: 'neutral', detail: 'Contexto creado' },
]
