export const serviceCatalog = {
  'Corte de cabello': [
    'Corte mujer',
    'Corte hombre',
    'Corte infantil',
    'Corte de puntas',
    'Corte de fleco',
    'Cambio de look',
    'Corte cabello rizado',
  ],
  Barberia: [
    'Corte clasico',
    'Fade/degradado',
    'Corte con maquina',
    'Corte con tijera',
    'Arreglo de barba',
    'Perfilado de barba',
    'Corte + barba',
  ],
  'Tinte / Coloracion': [
    'Tinte completo',
    'Retoque de raiz',
    'Cobertura de canas',
    'Bano de color',
    'Matizacion',
    'Tinte fantasia',
    'Cambio de color',
  ],
  'Mechas e iluminacion': [
    'Balayage',
    'Babylights',
    'Highlights',
    'Mechas tradicionales',
    'Money Piece',
    'Contouring',
    'Ombre',
    'Retoque de luces',
  ],
  'Decoloracion y correccion': [
    'Decoloracion global',
    'Decoloracion de raiz',
    'Extraccion de color',
    'Correccion de color',
    'Limpieza de color',
  ],
  Peinado: [
    'Secado',
    'Brushing',
    'Planchado',
    'Ondas',
    'Rizos',
    'Recogido',
    'Semirrecogido',
    'Peinado para evento',
  ],
  'Tratamientos capilares': [
    'Hidratacion',
    'Nutricion',
    'Reparacion',
    'Reconstruccion',
    'Tratamiento para cabello tenido',
    'Tratamiento antiencrespamiento',
    'Tratamiento cuero cabelludo',
  ],
  'Alisado y textura': [
    'Alisado',
    'Keratina',
    'Botox capilar',
    'Nanoplastia',
    'Permanente',
    'Ondulado permanente',
  ],
  Unas: [
    'Manicure',
    'Pedicure',
    'Gel semipermanente',
    'Acrilico',
    'Gel de construccion',
    'Polygel',
    'Press-on',
    'Retiro de producto',
  ],
  'Diseno de unas': [
    'Nail art sencillo',
    'Nail art avanzado',
    'Francesa',
    'Baby boomer',
    'Efectos',
    'Pedreria',
    'Diseno personalizado',
  ],
  Pestanas: [
    'Extensiones clasicas',
    'Hibridas',
    'Volumen',
    'Mega volumen',
    'Retoque de extensiones',
    'Retiro',
    'Lifting',
    'Tinte de pestanas',
  ],
  Cejas: [
    'Diseno de ceja',
    'Depilacion',
    'Laminado',
    'Tinte',
    'Henna',
    'Microblading',
    'Microshading',
    'Retoque',
  ],
  Maquillaje: [
    'Maquillaje social',
    'Dia',
    'Noche',
    'Glam',
    'Novia',
    'XV anos',
    'Graduacion',
    'Fotografia',
  ],
  Faciales: [
    'Limpieza facial',
    'Facial hidratante',
    'Facial antiacne',
    'Antiedad',
    'Piel sensible',
    'Luminosidad',
    'Facial personalizado',
  ],
  Depilacion: [
    'Cera',
    'Hilo',
    'Laser',
    'IPL',
  ],
  Masajes: [
    'Relajante',
    'Descontracturante',
    'Deportivo',
    'Drenaje linfatico',
    'Reductivo',
  ],
  'Tratamientos corporales': [
    'Reductivo',
    'Reafirmante',
    'Anticelulitis',
    'Drenaje',
    'Moldeo corporal',
    'Exfoliacion corporal',
  ],
  'Extensiones de cabello': [
    'Colocacion',
    'Retiro',
    'Mantenimiento',
    'Recolocacion',
    'Corte/adaptacion',
    'Peinado de extensiones',
  ],
  'Novias y eventos': [
    'Peinado novia',
    'Maquillaje novia',
    'Prueba de maquillaje',
    'Prueba de peinado',
    'Paquete novia',
    'XV anos',
    'Evento especial',
  ],
}

const serviceCategoryAliases = {
  'Colocacion de Unas': 'Unas',
  'Colocación de Uñas': 'Unas',
  'Colocacion de Uñas': 'Unas',
  'Colocación de Unas': 'Unas',
  'Colocacion de Pestanas': 'Pestanas',
  'Colocación de Pestañas': 'Pestanas',
  'Colocacion de Pestañas': 'Pestanas',
  'Colocación de Pestanas': 'Pestanas',
  Manicure: 'Unas',
  Pedicure: 'Unas',
  Microblading: 'Cejas',
  Depilado: 'Depilacion',
  Skincare: 'Faciales',
  Spa: 'Tratamientos corporales',
  Laminado: 'Cejas',
}

export function normalizeServiceCategory(category = '') {
  const cleanCategory = String(category || '').trim()
  return serviceCatalog[cleanCategory]
    ? cleanCategory
    : serviceCategoryAliases[cleanCategory] || cleanCategory || 'Servicios'
}

export const weeklyScheduleTemplate = [
  { day: 'Lunes', active: false, start: 'Libre', end: 'Libre', breakStart: '-', breakEnd: '-' },
  { day: 'Martes', active: false, start: 'Libre', end: 'Libre', breakStart: '-', breakEnd: '-' },
  { day: 'Miercoles', active: false, start: 'Libre', end: 'Libre', breakStart: '-', breakEnd: '-' },
  { day: 'Jueves', active: false, start: 'Libre', end: 'Libre', breakStart: '-', breakEnd: '-' },
  { day: 'Viernes', active: false, start: 'Libre', end: 'Libre', breakStart: '-', breakEnd: '-' },
  { day: 'Sabado', active: false, start: 'Libre', end: 'Libre', breakStart: '-', breakEnd: '-' },
  { day: 'Domingo', active: false, start: 'Libre', end: 'Libre', breakStart: '-', breakEnd: '-' },
]
