export const serviceCatalog = {
  'Colocacion de Unas': [
    'Unas acrilicas',
    'Unas en gel',
    'Unas postizas',
    'Ombre nails',
    'Diseno personalizado',
    'Nail art',
    'Unas decoradas',
    'Extension de unas',
    'Unas 3D',
  ],
  'Colocacion de Pestanas': [
    'Pestanas volumen ruso',
    'Pestanas volumen clasico',
    'Pestanas volumen hibrido',
    'Pestanas de seda',
    'Pestanas de vison',
    'Refuerzos de pestanas',
    'Desmaquillante de pestanas',
  ],
  Maquillaje: [
    'Maquillaje de novia',
    'Maquillaje casual',
    'Maquillaje de quinceanos',
    'Maquillaje de evento social',
    'Maquillaje de fiesta',
    'Maquillaje de graduacion',
    'Maquillaje artistico',
    'Maquillaje fantasia',
    'Maquillaje smoke eyes',
    'Maquillaje natural',
    'Maquillaje glam',
    'Maquillaje corporativo',
    'Maquillaje de sesion fotografica',
  ],
  Manicure: [
    'Manicure clasico',
    'Manicure frances',
    'Manicure gel',
    'Manicure spa',
    'Manicure con diseno',
    'Manicure semipermanente',
    'Manicure para eventos',
    'Manicure reparador',
    'Manicure con piedras',
  ],
  Pedicure: [
    'Pedicure clasico',
    'Pedicure frances',
    'Pedicure gel',
    'Pedicure spa',
    'Pedicure con diseno',
    'Pedicure semipermanente',
    'Pedicure para eventos',
    'Pedicure reparador',
    'Pedicure con piedras',
    'Pedicure terapeutico',
  ],
  Microblading: [
    'Microblading cejas',
    'Microblading con sombreado',
    'Microblading de pelo a pelo',
    'Diseno de cejas',
    'Correccion de cejas',
    'Micropigmentacion labios',
    'Micropigmentacion delineado',
  ],
  Faciales: [
    'Limpieza facial profunda',
    'Facial con acido glicolico',
    'Facial con acido salicilico',
    'Facial hidratante',
    'Facial antienvejecimiento',
    'Facial antiacne',
    'Facial descongestionante',
    'Facial con mascarilla de colageno',
    'Facial con retinol',
    'Facial vitaminico',
    'Peeling facial',
    'Facial luminoso',
    'Facial para pieles sensibles',
    'Facial oxigenante',
  ],
  Depilado: [
    'Depilacion con cera',
    'Depilacion con hilo',
    'Depilacion laser',
    'Depilacion de cejas',
    'Depilacion de bigote',
    'Depilacion de axilas',
    'Depilacion de piernas',
    'Depilacion de brazos',
    'Depilacion de espalda',
    'Depilacion de zona intima',
    'Depilacion facial',
    'Depilacion con azucar',
  ],
}

export const weeklyScheduleTemplate = [
  { day: 'Lunes', active: false, start: 'Libre', end: 'Libre', breakStart: '-', breakEnd: '-' },
  { day: 'Martes', active: false, start: 'Libre', end: 'Libre', breakStart: '-', breakEnd: '-' },
  { day: 'Miercoles', active: false, start: 'Libre', end: 'Libre', breakStart: '-', breakEnd: '-' },
  { day: 'Jueves', active: false, start: 'Libre', end: 'Libre', breakStart: '-', breakEnd: '-' },
  { day: 'Viernes', active: false, start: 'Libre', end: 'Libre', breakStart: '-', breakEnd: '-' },
  { day: 'Sabado', active: false, start: 'Libre', end: 'Libre', breakStart: '-', breakEnd: '-' },
  { day: 'Domingo', active: false, start: 'Libre', end: 'Libre', breakStart: '-', breakEnd: '-' },
]
